name: Bump version

on:
  pull_request:
    types:
      - closed
    branches:
      - master
    paths-ignore:
      - ".github/**"
      - "version.properties"
  workflow_dispatch:

jobs:
  bump-version:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true && !startsWith(github.event.pull_request.head.ref, 'release/'))
    uses: personaClick/workflow/.github/workflows/reusable-multiplatform-version-bump.yaml@master
    permissions: write-all
    secrets:
      appSecret: ${{ secrets.PERSONACLICK_COURIER_SECRET }}
    with:
      appId: ${{ vars.PERSONACLICK_COURIER_ID }}
      reviewerUsername: iwwwanow
